apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${{ values.hostname }}
      secretName: ${{ values.name }}-tls
  rules:
    - host: ${{ values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.name }}
                port:
                  number: 8080
