apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.name }}-secrets
  namespace: ${{ values.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ${{ values.name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin_password
      remoteRef: { key: ${{ values.vaultPath }}, property: admin_password }
    - secretKey: db_root_password
      remoteRef: { key: ${{ values.vaultPath }}, property: db_root_password }
    - secretKey: encryption_key
      remoteRef: { key: ${{ values.vaultPath }}, property: encryption_key }
